name: Setup Database Credentials
description: Loads and formats database credentials based on repository and branch

inputs:
  repository:
    required: true
    description: Repository name
  branch:
    required: true
    description: Branch name
  db_prod:
    required: false
    description: DB_PROD secret
  db_dev:
    required: false
    description: DB_DEV secret
  db_dev_v2:
    required: false
    description: DB_DEV_V2 secret
  base_url:
    required: false
    description: BASE_URL secret (optional)
  send_email_url:
    required: false
    description: SEND_EMAIL_URL secret (optional)
  app_url:
    required: false
    description: APP_URL secret (optional)
  email_template:
    required: false
    description: EMAIL_TEMPLATE secret (optional)

outputs:
  db_env_vars:
    description: Formatted database environment variables string
    value: ${{ steps.setup.outputs.db_env_vars }}

runs:
  using: composite
  steps:
    - name: Set Database Credentials
      id: setup
      shell: bash
      run: |
        REPO="${{ inputs.repository }}"
        BRANCH="${{ inputs.branch }}"
        
        # Determine which DB credentials secret to use based on repo and branch
        if [[ "$REPO" == "jktech-training/skill-matrix" ]] && [[ "$BRANCH" == "main" ]]; then
          DB_ENV_VARS="${{ inputs.db_prod }}"
          echo "Using DB credentials for: skill-matrix (main/production)"
        elif [[ "$REPO" == "jktech-training/skill-matrix" ]] && [[ "$BRANCH" != "main" ]]; then
          DB_ENV_VARS="${{ inputs.db_dev }}"
          echo "Using DB credentials for: skill-matrix (development)"
        elif [[ "$REPO" == "jktech-training/skill-matrix-V2" ]] && [[ "$BRANCH" != "main" ]]; then
          DB_ENV_VARS="${{ inputs.db_dev_v2 }}"
          echo "Using DB credentials for: skill-matrix-V2 (development)"
        else
          DB_ENV_VARS="${{ inputs.db_dev_v2 }}"
          echo "Using default DB credentials (DB_DEV_V2)"
        fi
        
        # Convert newlines to commas for gcloud --set-env-vars format
        DB_ENV_VARS=$(echo "$DB_ENV_VARS" | grep -v '^[[:space:]]*$' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | tr '\n' ',' | sed 's/,$//')
        
        # Add environment-specific variables if they exist in separate secrets
        BASE_URL_SECRET="${{ inputs.base_url }}"
        SEND_EMAIL_URL_SECRET="${{ inputs.send_email_url }}"
        APP_URL_SECRET="${{ inputs.app_url }}"
        EMAIL_TEMPLATE_SECRET="${{ inputs.email_template }}"
        
        if [[ "$DB_ENV_VARS" != *"BASE_URL="* ]] && [[ -n "$BASE_URL_SECRET" ]]; then
          DB_ENV_VARS="$DB_ENV_VARS,BASE_URL=$BASE_URL_SECRET"
        fi
        
        if [[ "$DB_ENV_VARS" != *"SEND_EMAIL_URL="* ]] && [[ -n "$SEND_EMAIL_URL_SECRET" ]]; then
          DB_ENV_VARS="$DB_ENV_VARS,SEND_EMAIL_URL=$SEND_EMAIL_URL_SECRET"
        fi
        
        if [[ "$DB_ENV_VARS" != *"APP_URL="* ]] && [[ -n "$APP_URL_SECRET" ]]; then
          DB_ENV_VARS="$DB_ENV_VARS,APP_URL=$APP_URL_SECRET"
        fi
        
        if [[ "$DB_ENV_VARS" != *"EMAIL_TEMPLATE="* ]] && [[ -n "$EMAIL_TEMPLATE_SECRET" ]]; then
          DB_ENV_VARS="$DB_ENV_VARS,EMAIL_TEMPLATE=$EMAIL_TEMPLATE_SECRET"
        fi
        
        echo "db_env_vars=$DB_ENV_VARS" >> $GITHUB_OUTPUT
        echo "✅ Environment variables loaded successfully"
